cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'awscli'
brew 'git-lfs'
brew 'gh'
brew 'git-standup'
brew 'jq'
brew 'wget'
brew 'yt-dlp/taps/yt-dlp'

cask '1password'
cask 'appcleaner'
cask 'firefox'
cask 'obsidian'
cask 'rectangle'
cask 'signal'
cask 'transmission'
cask 'visual-studio-code'
cask 'vlc'
cask 'whatsapp'
