cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'awscli'
brew 'coreutils'
brew 'elixir'
brew 'git-lfs'
brew 'go'
brew 'gh'
brew 'grc' # colorize logfiles and commands
brew 'imagemagick'
brew 'fd' # alternative to find
brew 'git-standup'
brew 'jq'
brew 'node'
brew 'parquet-tools'
brew 'pgcli'
brew 'python3'
brew 'rbenv'
brew 'wifi-password'
brew 'wget'
brew 'yt-dlp/taps/yt-dlp'

cask '1password'
cast 'appcleaner'
cask 'dash'
cask 'firefox'
cask 'fork'
cask 'iterm2'
cask 'obsidian'
cask 'postman'
cask 'rectangle'
cask 'signal'
cask 'spotify'
cask 'tableplus'
cask 'transmission'
cask 'visual-studio-code'
cask 'vlc'
cast 'whatsapp'
